# Generated by Django 3.0.3 on 2020-09-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_email_id', models.CharField(choices=['all', 'students', 'faculty'], max_length=20)),
                ('primary_mobile_no', models.CharField(choices=['all', 'students', 'faculty'], max_length=20)),
                ('room_no', models.CharField(choices=['all', 'students', 'faculty'], max_length=20)),
                ('bhawan', models.CharField(choices=['all', 'students', 'faculty'], max_length=20)),
            ],
        ),
    ]
