# Generated by Django 3.0.3 on 2020-10-03 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_STUDENT_MODEL),
        ('people_search', '0002_auto_20200927_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_search_student', to=settings.KERNEL_STUDENT_MODEL, unique=True),
        ),
    ]
