# Generated by Django 3.0.3 on 2020-09-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_search', '0002_profile_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bhawan',
            field=models.CharField(choices=[('all', 'All'), ('students', 'All Students'), ('faculty', 'All Faculty')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_email_id',
            field=models.CharField(choices=[('all', 'All'), ('students', 'All Students'), ('faculty', 'All Faculty')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_mobile_no',
            field=models.CharField(choices=[('all', 'All'), ('students', 'All Students'), ('faculty', 'All Faculty')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='room_no',
            field=models.CharField(choices=[('all', 'All'), ('students', 'All Students'), ('faculty', 'All Faculty')], default='all', max_length=20),
        ),
    ]
